Segmentacao/config/routes.rb
Rails.application.routes.draw do
  resources :contatos
   
   root :to => "contatos#index"   
   get "listaAnd" => "contatos#listaAnd" 
   get "listaOr" => "contatos#listaOr" 
  
   
  # The prioority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Segmentacao/app/models/contato.rb
class Contato < ActiveRecord::Base
end

Segmentacao/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Segmentacao/app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  	  
  def listaAnd	
		@contatos = Contato.where("estado like 'sc' and idade > '30'")
  end
  
   def listaOr	
		@contatos = Contato.where("cargo like 'diretor de marketing' or estado like 'sp' ")
  end
  
  def index
	if params[:estado]
		@contatos = Contato.where("estado like '%#{params[:estado]}%' and idade = '#{params[:idade]}'")
	else
		@contatos = Contato.all
	end
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :idade, :estado, :cargo)
    end
end

Segmentacao/app/helpers/application_helper.rb
module ApplicationHelper
end

Segmentacao/app/helpers/contatos_helper.rb
module ContatosHelper
end

Segmentacao/app/views/contatos/_form.html.erb
<%= form_for(@contato) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.text_field :idade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Segmentacao/app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @contato %> |
<%= link_to 'Voltar', contatos_path %>

Segmentacao/app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Todos de Contatos</h1>
<%= form_tag(contatos_path, :method => :get) do %>
	<%= text_field_tag 'estado', nil, placeholder: 'Digite o estado'%> &nbsp;E&nbsp;	
	<%= text_field_tag 'idade', nil, placeholder: 'Digite a idade'%>
	<%= submit_tag "Pesquisar" %>
<%end%>
<br>
<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Idade</th>
      <th>Estado</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.idade %></td>
        <td><%= contato.estado %></td>
        <td><%= contato.cargo %></td>
        <td><%= link_to 'Detalhes', contato %></td>
        <td><%= link_to 'Editar', edit_contato_path(contato) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>Resultados pré-definidos</h1>

<%= link_to 'Lista de Contatos por Estado E Idade > 30', listaAnd_path %>
<br>
<br>
<%= link_to 'Lista de Contatos por Cargo OU Estado', listaOr_path %>
<br>
<br>
<h1>Cadastrar</h1>
<%= link_to 'Incluir contato', new_contato_path %>

Segmentacao/app/views/contatos/listaAnd.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de Contatos por Estado e Idade > 30</h1>

<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Idade</th>
      <th>Estado</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.idade %></td>
        <td><%= contato.estado %></td>
        <td><%= contato.cargo %></td>
        <td><%= link_to 'Detalhes', contato %></td>
        <td><%= link_to 'Editar', edit_contato_path(contato) %></td>
        <td><%= link_to 'Deletar', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Página principal', contatos_path %>
<br>

Segmentacao/app/views/contatos/listaOr.html.erb
<p id="notice"><%= notice %></p>
<h1>Lista de Contatos por Cargo OU Estado</h1>

<table border="1">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Idade</th>
      <th>Estado</th>
      <th>Cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.idade %></td>
        <td><%= contato.estado %></td>
        <td><%= contato.cargo %></td>
        <td><%= link_to 'Detalhes', contato %></td>
        <td><%= link_to 'Editar', edit_contato_path(contato) %></td>
        <td><%= link_to 'Deletar', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Página principal', contatos_path %>
<br>

Segmentacao/app/views/contatos/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form' %>

<%= link_to 'Back', contatos_path %>

Segmentacao/app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @contato.idade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @contato.estado %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @contato.cargo %>
</p>

<%= link_to 'Editar', edit_contato_path(@contato) %> |
<%= link_to 'Voltar', contatos_path %>

Segmentacao/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Segmentacao</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>